version: '3'
services:
  metronome:
    build: .
    ports:
      - "3001"  # Замените на нужный порт
    volumes:
      - ./playwright-report:/app/playwright-report
    command: >
      sh -c "npm run dev & sleep 10 && npm run test"