services:
  metronome:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./:/metronome-app
      - /metronome-app/node_modules
    command: npm run dev
    profiles: ["dev", "default"]


  metronome-test:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/metronome-app
      - /metronome-app/node_modules
      - ./playwright-report:/app/playwright-report
    command: >
      sh -c "npm run dev & npx wait-on -t 20000 http://localhost:3001 && npm run test"
    profiles: ["test"]