services:
  metronome:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./playwright-report:/metronome-app/playwright-report
    command: >
      sh -c "npm run start:ci & npx wait-on http://localhost:3001 && npm run test"