version: '3'
services:
  metronome:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./playwright-report:/app/playwright-report
    command: >
      sh -c "npm run dev & npx wait-on http://localhost:3001 && npm run test"