name: app testing

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Настройка Docker
        uses: docker/setup-buildx-action@v3

      - name: Сборка и запуск тестов
        run: |
          docker build -t metronome-test .
          docker compose up --abort-on-container-exit

      - name: Сохранение отчетов Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30