name: app testing

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: build and run tess
        run: |
          docker build -t metronome-test .
          docker compose --profile test up --abort-on-container-exit

      - name: save test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30