name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
        env:
          NODE_OPTIONS: '--no-deprecation'

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build

      - name: Start server and run e2e tests
        run: |
          npm run start:ci & 
          npx wait-on http://localhost:3001
          npm run test:e2e
        env:
          PLAYWRIGHT_CHROMIUM_ARGS: "--no-sandbox --autoplay-policy=no-user-gesture-required --enable-webaudio --enable-audio-service-sandbox --enable-audio-input"
          PLAYWRIGHT_WEBKIT_ARGS: "--enable-webaudio --enable-webgl --enable-media-capabilities --enable-media-stream"
          PLAYWRIGHT_FIREFOX_ARGS: "--no-sandbox --use-gl=swiftshader --enable-webgl --enable-media-stream"
          # Дополнительные переменные окружения для решения проблем с аудио
          NODE_OPTIONS: "--max-old-space-size=4096"
          PLAYWRIGHT_SKIP_BROWSER_GC: "1"
          DISPLAY: ":99.0"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # Дополнительный job для запуска в headless режиме с разными конфигурациями
  e2e-headless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup virtual display
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

      - name: Build app
        run: npm run build

      - name: Start server and run e2e tests in headless mode
        run: |
          npm run start:ci &
          npx wait-on http://localhost:3001
          DISPLAY=:99 xvfb-run --auto-servernum npx playwright test
        env:
          PLAYWRIGHT_BROWSERS_PATH: "0"
          PLAYWRIGHT_CHROMIUM_ARGS: "--no-sandbox --autoplay-policy=no-user-gesture-required --enable-webaudio --enable-audio-service-sandbox"
          PLAYWRIGHT_WEBKIT_ARGS: "--enable-webaudio --enable-webgl --no-sandbox"
          PLAYWRIGHT_FIREFOX_ARGS: "--no-sandbox --use-gl=swiftshader --enable-webgl --enable-media-stream"
          PLAYWRIGHT_SKIP_VALIDATION: "1"